### PR TITLE
Upstream of internal work

### PR DESCRIPTION
**Pull request by tmplt**
Following from https://github.com/atsams-rs/atsamx7x-rust/discussions/24, here is the PR for the work done internally at @GrepitAB.

Peripheral implementations added in this PR are:
- AFEC (ADC measurements);
- clock hierarchy (exhaustive);
- EFC (wait states, so far);
- PIO (almost exhaustive);
- PWM;
- RTT;
- UART, USART (SPI and UART modes), SPI, TWI (I2C);
- TC (frequency measurements, signal generation RTIC for scheduling primitives);
- watchdog (only WDT; can be disabled so far).

Examples for most peripherals are available for the V71 and E70 evaluation kits under `boards/*/examples`.
All modules have doc tests that run in CI.

Other changes:
- License change from 0BSD to MIT/Apache 2.0;
- Removal of the `cmsis-svd` submodule in favor of in-repo vendoring;
- Replaced `update.py` with `update-pacs.sh`;
- Removed workspace `Cargo.lock`.

There are a lot of changes in this PR. I suggest doing a surface-level review and checking `cargo doc`, and postponing implementation review to suitable issues/discussions. 

When merged I have some release branches and tags to push.

### CODE REVIEW

**Comment by tmplt** [comment]
Marked as draft until the Gitlab CI has been ported to GitHub Actions.

**Comment by tmplt** [comment]
Note: on the 19th this month I start a 9 month sabbatical. If I'm available at all, it will be infrequently. Hopefully we can have this merged before then, with CI (and maybe CD) setup and releases pushed to the crate registry.

**Comment by tmplt** [comment]
Many commits refer to internal Gitlab issues. I don't think its worth the work to scrub these from the history.

**Comment by tmplt** [comment]
CI has been ported. Pipeline can be seen at https://github.com/GrepitAB/atsams70-rust/actions?query=branch%3Adevelopment++.

**Comment by tmplt** [comment]
Closes #5, #17 (PAC publishing can be done via CD, TBD after this PR),

**Comment by michalfita** [comment]
> Many commits refer to internal Gitlab issues. I don't think its worth the work to scrub these from the history.

I agree. Commit history shall be enough.

**Comment by tmplt** [comment]
Is there anything that is blocking the merge?

**Comment by michalfita** [comment]
Time.
I'm on it ATM.

**Comment by michalfita** [comment]
The check for missing feature in `build.rs` is impediment to operations of `rust-analyzer`. I don't recall observing this problem when the check was in the code.

Raised #26.

**Comment by michalfita** [comment]
License of examples remains `0BSD` is this intentional?

**Comment by michalfita** [comment]
@tmplt the `CHANGELOG.md` contains description of following releases:
* 0.2.0
* 0.2.1
* 0.3.0

There are dates, but tags doesn't seem to be part of the merge. Could you please provide what commits they're at?

**Comment by michalfita** [comment]
@tmplt are you sure all OpenOCD and Probe files in examples shall be left there?

**Comment by tmplt** [comment]
> License of examples remains 0BSD is this intentional?

No; fixed.

> tags doesn't seem to be part of the merge. Could you please provide what commits they're at?

I'm not sure I can push them without direct write access, but here are my local tags:

```
$ git show-ref --tags
afffd2f8b45cbc9dbf1881be3849217161780e5a refs/tags/v0.0.1
6565a99377db749e39f2c8015a5c753817a09ad3 refs/tags/v0.0.2
6ca1a9e803f8a21b0a625ca797b52d9e0f446555 refs/tags/v0.2.0
6ca068809e3dbebf639b99e112609ceaf36e1a16 refs/tags/v0.2.1
4ec7b576bb5a7a15b73f2cb3eadec5731902bd9e refs/tags/v0.3.0
```

> are you sure all OpenOCD and Probe files in examples shall be left there?

Yes, they are only for the devkits anyway. Ideally we could remove the openocd scripts, but the GDB-stub of `cargo-embed` is not very useful, so they are there for convenience.

**Pull request merged**
