### PR TITLE
Regenerate PACs with svd2rust 0.21.0, replace LFS pointers with submodule

### PR DESCRIPTION
**Pull request by tmplt**
This PR
- replaces the LFS-stored PACs with a submodule to an [unofficial SVD mirror](https://github.com/posborne/cmsis-svd/tree/master/data/Atmel) (see below why);
- regenerates all PACs with svd2rust 0.21.0;
- bump PAC versions to match svd2rust version;
- updates the HAL for the PAC API changes (`usart0` flushing only);
- gates HAL build behind the `device-selected` feature;
- renames the HAL to `atsamx7x-hal` to imply the support for the `ATSAM{E,S,V}7{1,2}*` MCUs. I also propose the repo is renamed to this.

The LFS usage has been replaced because all allowed bandwidth has been used up; I was not able to `git lfs fetch` the PACs. Instead of wrangling with that I believe it is beneficial to use an upstream repository that contains the SVDs we use.

This PR is a draft because the SVDs for the ATSAMS MCUs are currently missing from the CMSIS-SVD repo. These should be added there and this PR amended before merge.

### CODE REVIEW

**Comment by tmplt** [comment]
I'm unsure if GitHub pings the maintainer on draft PRs, so @michalfita.

**Comment by tmplt** [comment]
ATSAMS PACs have now been generated. We should wait for https://github.com/posborne/cmsis-svd/pull/149 before merge.

Names of some registers differ across devices, e.g. `us_csr` c.f. `us_csr_{lin,lon,lon_spi,usart_lin,usart}_mode`. I do not know why this is the case. Best approach may be to patch the SVDs.

**Comment by michalfita** [comment]
@tmplt Thank you. Looks promising. A few aspects to address in general:

1. Why sudden interest in that? Is it related to my appeal on Matrix?
2. I'm planning to move this repo into [atsams-rs](https://github.com/atsams-rs) organization. Can rename the repo in the mean time to `atsamx7x-rust`.
   Q: Are you interested to become the member of the organization? I'd still prefer PRs for work happening there (_even if I cannot probably actively work on it at the moment_)
3. I'm working on PR with SVD for the [CMSIS-SVD repo](https://github.com/posborne/cmsis-svd) at the moment. Will post link to the PR here soon.
4. While it makes sense to use common repository of SVD files, the downside is that from now on everyone would have to clone the whole CMSIS-SVD repo, while it would make sense for them to create the organisation and keep one repo per manufacturer.
5. The structure of the submodule has a few level of depths that needs to be addressed. They I suggest `svd` is renamed to `cmsis-svd` as submodule cannot point at the subdirectory of another repository.

**Comment by michalfita** [comment]
https://github.com/posborne/cmsis-svd/pull/150 is the PR for missing SVD files.

**Comment by michalfita** [comment]
> ATSAMS PACs have now been generated. We should wait for https://github.com/posborne/cmsis-svd/pull/149 before merge.

@tmplt Your PR doesn't add SAMV70, look at mine https://github.com/posborne/cmsis-svd/pull/150

**Comment by michalfita** [comment]
> Names of some registers differ across devices, e.g. us_csr c.f. us_csr_{lin,lon,lon_spi,usart_lin,usart}_mode. I do not know why this is the case. Best approach may be to patch the SVDs.

I'd be careful, in a few cases I've checked these are reflected in Data Sheets.

**Comment by tmplt** [comment]
> Why sudden interest in that? Is it related to my appeal on Matrix?

We'll be using several ATSAM variants internally at @GrepitAB, hence this PR. Adding support for the V variant was initially investigated for [atsamd-hal](https://crates.io/crates/atsamd-hal), but the peripheral layouts were deemed too different to support it in the HAL. See https://github.com/atsamd-rs/atsamd/pull/572.

> I'm planning to move this repo into [atsam-rs](https://github.com/atsams-rs) organization.

The ecosystem currently appears fragmented: there is also https://github.com/atsamd-rs and https://github.com/atsam-rs. Do you know if there is some effort to collect all ATSAM crates in a single place?

> Can rename the repo in the mean time to atsamx7x-rust.

Sure.

> Q: Are you interested to become the member of the organization?

Yes. There will be more contributions from my end.

> While it makes sense to use common repository of SVD files, the downside is that from now on everyone would have to clone the whole CMSIS-SVD repo

This is not much different from the previous LFS approach: a new contributor would have to fetch all the SVDs, but this was not possible due to the bandwidth limit.

> while it would make sense for them to create the organisation and keep one repo per manufacturer.

I don't understand. Could you elaborate?

> They I suggest svd is renamed to cmsis-svd as submodule cannot point at the subdirectory of another repository.

Agreed. I'll amend when https://github.com/posborne/cmsis-svd/pull/150 has been merged.

> I'd be careful, in a few cases I've checked these are reflected in Data Sheets.

If that's the case then the different registers should of course be accounted for, and not be patched without good reason. I have yet to look too deeply into the register definitions between the variants.

**Comment by michalfita** [comment]
> We'll be using several ATSAM variants internally at https://github.com/GrepitAB, hence this PR. Adding support for the V variant was initially investigated for [atsamd-hal](https://crates.io/crates/atsamd-hal), but the peripheral layouts were deemed too different to support it in the HAL. See https://github.com/atsamd-rs/atsamd/pull/572.

ATSAMDxx are completely different family and they don't share peripherals, not only layout wise, but functional wise as well. I know designs of them come from different teams in Atmel.

It's interesting the sudden interest in this family and Rust came from two different angles. The gentleman who approached me is going to benefit from all work that will happen here.

> The ecosystem currently appears fragmented: there is also https://github.com/atsamd-rs and https://github.com/atsam-rs. Do you know if there is some effort to collect all ATSAM crates in a single place?

It's not that bad - all three organisations are taking responsibility for three distinctive families of ARM MCUs from Atmel/Microchip. There was typo in my post (the link was right) and I meant [atsams-rs](https://github.com/atsams-rs) organization. I wonder if @jamesmunns or someone from @ferrous-systems is going to join...

> This is not much different from the previous LFS approach: a new contributor would have to fetch all the SVDs, but this was not possible due to the bandwidth limit.

They had to fetch only SAMx7x SVD files, now it's much more and they're large. And then within the submodule we have to navigate their directory tree - I wonder if leaving `svd` as symlink to the `data/Atmel` directory in `cmsis-svd` submodule wouldn't make sense, would it?

> >  while it would make sense for them to create the organisation and keep one repo per manufacturer.
>
> I don't understand. Could you elaborate?

See the explanation above. There's a lot of data to clone with SVDs for all brands supported by that repo.

We should move that discussion to discussions and leave this PR's thread for the PR.

**Comment by michalfita** [comment]
@tmplt These changes? AFAIR I had them in a template and regenerated automatically from the script, just to avoid error prone manual copy&paste. Wouldn't be wide to follow that practice?

**Comment by tmplt** [comment]
Michał Fita ***@***.***> writes:
> @tmplt These changes? AFAIR I had them in a template and regenerated
> automatically from the script, just to avoid error prone manual
> copy&paste. Wouldn't be wide to follow that practice?

That is what I did. I updated the template and ran ./update.py.

**Comment by michalfita** [comment]
I was thinking more about expanding the process to cover regeneration of `hal/Cargo.toml`.

**Comment by tmplt** [comment]
Michał Fita ***@***.***> writes:
> I was thinking more about expanding the process to cover regeneration of `hal/Cargo.toml`.

Ah, yes, that would be beneficial.

**Comment by jamesmunns** [comment]
Just as a note, I'm also attempting to work on SAME70 support, and even having LFS enabled while using @tmplt's fork means that I can't do any git operations, due to the over-quota messages.

For now, I'll do a hard-fork of the SAME70 project, but if there is some way to merge the submodule work, and squash away the history that expects/uses LFS, that would be awesome.

**Comment by tmplt** [comment]
>but if there is some way to merge the submodule work, and squash away the history that expects/uses LFS

You should be able to base your work on this branch, no? I have had no issues with LFS getting in the way after the first fetch try, now that HEAD have removed all LFS references. But I interface with git via porcelain (magit), perhaps the behavior differs.

**Comment by jamesmunns** [comment]
@tmplt yeah, it's possible there was a way for it to work, though I tried to pull this branch, and push it to my fork, however I received errors about LFS over quota.

I don't commonly work with git-lfs, so I'm not sure how to configure the repo locally to "ignore" it.

**Comment by michalfita** [comment]
@jamesmunns and @tmplt Let me try something if it's my quota that's depleted. I'll move the repo to the organisation now - it should get a new quota.

@tmplt let's get this PR ready to merge, OK?

**Comment by michalfita** [comment]
OK, for now on it's not my own repository any more. @jamesmunns You've been invited to the organization as well.

Hopefully the organization has it's own LFS quota and you can use it to fully clone and start working.

@tmplt The https://github.com/posborne/cmsis-svd/pull/150#pullrequestreview-893996428 is merged now - is there anything else stoping you from finishing this PR now?

**Comment by tmplt** [comment]
I found no obvious good approach to generate `hal/Cargo.toml` right now. I propose we postpone that change for a later PR.

**Comment by tmplt** [comment]
The HAL may not necessarily build with every PAC in mind: I have not tested all of them. A CI would be apt but I think that is better fit for a separate PR.

**Comment by michalfita** [comment]
Thanks, @tmplt. I'm going to collect ideas and postponed work in https://github.com/orgs/atsams-rs/projects/1; for now these are drafts, but they may be turned into issues, that can be closed by PRs when merged.

**Comment by michalfita** [comment]
I can't review this last commit you've force-pushed - I think all changes are accumulated, and GitHub cannot load them. This over 5000+ files puzzles me...

**Comment by tmplt** [comment]
Locally,
```
$ find pac | wc -l
52208
```
so Github reports it correctly: each register has its own file and we have 67 (!) PACs. I do not know what the best approach is to review PRs as large as this, but you will probably have an easier time doing it locally.

**Comment by michalfita** [comment]
I have only `49155` in `pac`, so there is some large number or you count with binaries... I'm trying to take a look locally.

**Comment by michalfita** [comment]
Notes:
* `README.md.template` has Windows' new line character committed.
* ~Where the `0.21.0` version for PACs comes from?~ Ignore: version of `svd2rust` used.
* `-all_svd_files = glob.glob("./svd/*.svd")` => `+all_svd_files = glob.glob("./svd/ATSAM[E,S,V]7[0,1]*.svd")` were there any rogue SVDs there?

Does other projects like that keep PACs crates in separated repos? It starts to look like maintenance hell if kept together? @jamesmunns what are _idoms_ in that regard followed elsewhere?

**Comment by tmplt** [comment]
>  It starts to look like maintenance hell if kept together?

How so? Changing to this submodule approach is a one time cost, presuming that Atmel does not release any new revisions.

> Does other projects like that keep PACs crates in separated repos?

Not what I have seen. Most other HALs ship the SVDs in the same repo, without LFS.

> were there any rogue SVDs there?

Could you elaborate?

**Comment by michalfita** [comment]
> Not what I have seen. Most other HALs ship the SVDs in the same repo, without LFS.

Let's leave it this way. It's just anyone cloning would have to pull 50k files.

> Could you elaborate?

You've applied `./svd/ATSAM[E,S,V]7[0,1]*.svd` pattern to the `glob()` what looks like attempt to avoid some files you don't want to deal with.

**Comment by tmplt** [comment]
> what looks like attempt to avoid some files you don't want to deal with.

Correct. The directory also contains SVDs for other families, e.g. the `ATSAM[D,E]5*` family, handled by the atsamd crate.

**Comment by michalfita** [comment]
@tmplt I cannot approve it from here as approvals work from files section which will not open with 50k files... merging.

**Pull request merged**
