### PR TITLE
ADC Example tested on Xult/EXT-1 PIN#4 (PA19/AFEC0_AD8)

### PR DESCRIPTION
**Pull request by blietaer**
Well, I just tested it on the Xult/EXT-1 PIN#4 (PA19/AFEC0_AD8), working fine: shall I commit the change ?

### CODE REVIEW

**Review by tmplt — CHANGES_REQUESTED** [review]
LGTM, but I cannot test it. Add an entry to the changelog and I'll approve.

**Comment by blietaer** [comment]
CHANGELOG.md updated on my forked branch.

**Review by tmplt — APPROVED** [review]
Looks like we have new linting rules.

**Comment by michalfita** [comment]
@tmplt you meant failed CI? We build with MRV and latest to spot problems preventing users of newer compilers from using our crates. Most problems are addressed on branches waiting to be sort out and final release.

**Pull request merged**
